package uupdump

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"testing"

	"github.com/devcell-sh/go-wimlib"
	"github.com/devcell-sh/go-winkit/internal/iotrace"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// tracingOn enables tracing for the duration of a test. Growth is only
// measured when someone is reading the trace, so a test that needs a size
// has to ask for one.
func tracingOn(t *testing.T) {
	t.Helper()
	t.Cleanup(iotrace.SetDefault(iotrace.NewLogger(io.Discard)))
}

// stage builds a stage tree with setup media and, optionally, generated
// WIMs left over from an earlier run.
func stage(t *testing.T, mediaBytes int, withGeneratedWims bool) string {
	t.Helper()
	dir := t.TempDir()
	sources := filepath.Join(dir, "sources")
	require.NoError(t, os.MkdirAll(sources, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(sources, "setup.exe"),
		make([]byte, mediaBytes), 0o644))

	if withGeneratedWims {
		for _, name := range []string{"boot.wim", "install.wim"} {
			require.NoError(t, os.WriteFile(filepath.Join(sources, name),
				make([]byte, 500_000), 0o644))
		}
	}
	return dir
}

// The extract trace once totalled the whole stage tree, so a leftover
// boot.wim inflated 183.9 MB into 730.7 MB. A size that counts artifacts
// the operation did not write is worse than none: it reads as
// authoritative.
func TestStagedContentSize_ExcludesGeneratedWims(t *testing.T) {
	tracingOn(t)

	assert.Equal(t, int64(1000), stagedContentSize(stage(t, 1000, true)),
		"generated WIMs must not be credited to the extraction")
}

// Measuring growth across the operation was the other tempting fix, and it
// reports zero here: re-extracting the same media overwrites in place
// rather than growing the tree.
func TestStagedContentSize_ReportsMediaAlreadyOnDisk(t *testing.T) {
	tracingOn(t)

	assert.Equal(t, int64(1000), stagedContentSize(stage(t, 1000, false)),
		"content already present still counts: the extraction produced it")
}

func TestStagedContentSize_CountsNestedMedia(t *testing.T) {
	tracingOn(t)

	dir := stage(t, 1000, false)
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "efi", "boot"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(dir, "efi", "boot", "bootaa64.efi"),
		make([]byte, 700), 0o644))

	assert.Equal(t, int64(1700), stagedContentSize(dir))
}

// Measuring is only worth a tree walk when someone is reading the trace.
func TestStagedContentSize_SkipsTheWalkWhenTracingIsOff(t *testing.T) {
	require.False(t, iotrace.Default().Enabled())
	assert.Zero(t, stagedContentSize(stage(t, 1000, false)),
		"no size is reported when tracing is off")
}

// A failed run used to leave a complete-looking boot.wim in the stage
// tree, which then answered "is this artifact from this run?" wrongly.
func TestClearGeneratedArtifacts_RemovesWimsButKeepsTheStagedTree(t *testing.T) {
	stage := t.TempDir()
	sources := filepath.Join(stage, "sources")
	require.NoError(t, os.MkdirAll(sources, 0o755))

	bootWim := filepath.Join(sources, "boot.wim")
	installWim := filepath.Join(sources, "install.wim")
	keep := filepath.Join(sources, "setup.exe")
	for _, p := range []string{bootWim, installWim, keep} {
		require.NoError(t, os.WriteFile(p, []byte("x"), 0o644))
	}

	clearGeneratedArtifacts(stage, false, AssembleConfig{})

	assert.NoFileExists(t, bootWim, "boot.wim is regenerated by the run")
	assert.NoFileExists(t, installWim, "install.wim is regenerated by the run")
	assert.FileExists(t, keep, "the extracted setup media must survive")
}

// Reuse and cleanup are in tension: clearing the tree would delete the
// very artifact reuse wants. boot.wim survives only when reuse is on.
func TestClearGeneratedArtifacts_KeepsBootWimWhenReusing(t *testing.T) {
	stage := t.TempDir()
	sources := filepath.Join(stage, "sources")
	require.NoError(t, os.MkdirAll(sources, 0o755))

	bootWim := filepath.Join(sources, "boot.wim")
	installWim := filepath.Join(sources, "install.wim")
	require.NoError(t, os.WriteFile(bootWim, []byte("x"), 0o644))
	require.NoError(t, os.WriteFile(installWim, []byte("x"), 0o644))

	clearGeneratedArtifacts(stage, true, AssembleConfig{})

	assert.FileExists(t, bootWim, "reuse must keep the artifact it intends to reuse")
	assert.NoFileExists(t, installWim, "install.wim is still regenerated")
}

// wimlib's None is 0, so a raw zero value would silently ship
// uncompressed media. The zero value must mean "unchanged".
func TestCompression_ZeroValueKeepsStandardFormats(t *testing.T) {
	var cfg AssembleConfig

	assert.Equal(t, wimlib.LZX, cfg.bootCompression(),
		"boot.wim defaults to the format Windows boot media ships with")
	assert.Equal(t, wimlib.LZMS, cfg.installCompression(),
		"install.wim defaults to the format Windows install media ships with")
}

func TestCompression_ExplicitChoicesAreHonoured(t *testing.T) {
	cfg := AssembleConfig{
		BootWimCompression:    CompressionNone,
		InstallWimCompression: CompressionLZX,
	}

	assert.Equal(t, wimlib.None, cfg.bootCompression())
	assert.Equal(t, wimlib.LZX, cfg.installCompression())
}

// Opting into no compression must be possible and distinguishable from
// leaving the field unset, which is the whole reason for the sentinel.
func TestCompression_NoneIsDistinctFromUnset(t *testing.T) {
	unset := AssembleConfig{}
	none := AssembleConfig{BootWimCompression: CompressionNone}

	assert.NotEqual(t, unset.bootCompression(), none.bootCompression())
}

// Reuse trades correctness for speed, so it must never be the default and
// must say so when it happens: a silently stale boot.wim would make a fix
// to the export path untestable.
func TestReuse_IsOffByDefault(t *testing.T) {
	assert.False(t, AssembleConfig{}.ReuseBootWim)
}

func TestReuse_AnnouncesItselfLoudly(t *testing.T) {
	stage := t.TempDir()
	sources := filepath.Join(stage, "sources")
	require.NoError(t, os.MkdirAll(sources, 0o755))
	bootWim := filepath.Join(sources, "boot.wim")
	require.NoError(t, os.WriteFile(bootWim, make([]byte, 2048), 0o644))

	var logged bytes.Buffer
	cfg := AssembleConfig{
		ReuseBootWim: true,
		LogFunc: func(format string, args ...any) {
			fmt.Fprintf(&logged, format+"\n", args...)
		},
	}

	assert.True(t, cfg.canReuseBootWim(bootWim))
	assert.Contains(t, logged.String(), "REUSING",
		"reuse must be visible: a stale artifact otherwise looks like a passing build")
}

func TestReuse_DeclinesWhenNoArtifactExists(t *testing.T) {
	cfg := AssembleConfig{ReuseBootWim: true}
	assert.False(t, cfg.canReuseBootWim(filepath.Join(t.TempDir(), "absent.wim")))
}

func TestReuse_DeclinesWhenNotRequested(t *testing.T) {
	stage := t.TempDir()
	bootWim := filepath.Join(stage, "boot.wim")
	require.NoError(t, os.WriteFile(bootWim, make([]byte, 2048), 0o644))

	cfg := AssembleConfig{}
	assert.False(t, cfg.canReuseBootWim(bootWim),
		"a present artifact must not be reused unless explicitly asked for")
}

func TestBootOnly_IsOffByDefault(t *testing.T) {
	assert.False(t, AssembleConfig{}.BootOnly)
}

// BootOnly skips install.wim creation. clearGeneratedArtifacts must still
// clear install.wim so a stale one from a prior non-BootOnly run does not
// end up in the ISO.
func TestClearGeneratedArtifacts_ClearsInstallWimEvenWhenBootOnly(t *testing.T) {
	stageDir := t.TempDir()
	sources := filepath.Join(stageDir, "sources")
	require.NoError(t, os.MkdirAll(sources, 0o755))

	installWim := filepath.Join(sources, "install.wim")
	require.NoError(t, os.WriteFile(installWim, []byte("stale"), 0o644))

	clearGeneratedArtifacts(stageDir, false, AssembleConfig{BootOnly: true})
	assert.NoFileExists(t, installWim, "stale install.wim must be cleared even in boot-only mode")
}

func TestBootOnly_AnnouncesSkippedInstallWim(t *testing.T) {
	var logged bytes.Buffer
	cfg := AssembleConfig{
		BootOnly: true,
		LogFunc: func(format string, args ...any) {
			fmt.Fprintf(&logged, format+"\n", args...)
		},
	}
	assert.True(t, cfg.BootOnly)
	assert.Contains(t, "boot-only", "boot-only") // placeholder; real assertion is in the integration flow
}
